2025-03-13 04:10:14,522 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2025-03-13 04:10:14,570 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'ssh']
2025-03-13 04:10:14,580 DEBUG    root            Running [gcloud.compute.ssh] with arguments: [--command: "mkdir -p ~/.ssh && echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqCT4m+oCDHRyB1nMh+CjD7vS4235H2qmsUrOiA3rX1RYxan/4h1pCvpI4IFPkF+kEU81oGQ8bYcawGg7RLMhHzSs+Vw/ojPs897uYtc8uH68EUeu7IqxCj0fwBBTUl274QNi6e7AoaY9zxPNeL8Ft8FvoJuakoevsXlZqP5Nc/v2s0sEZyCqrlC+0MBRG/q4b7k8CpB3annXupV91hQEZWjD4W5M99XkdDcCXysnU64KRscD9UgTBxeUcRAaA5ObskGah6B1Q25ZkjUeDN6VleLoITFAu3ckePESldfNxs3mNVOzSJbYeKQ6P+2viZ8o2JddUkls+pgIrcj3XyCgzK6idvcq9A2gtrBJGxtmKmjd1ch0v+SMhm4l2t3Ezr9VjPe+CgmLW41g4S80HfxOWux8ldWwbchzqqJ9+suG+LkIFhmzgGcFwtde95aJ2w+zWBTvqM3bHaR4Y4/61v9LW6pnz1LEtW6J+8iRBugK3WXFPk8TtDRw40mDPX6OyNCM= aditya_tilak@instance-20250105-144000' >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys", [USER@]INSTANCE: "aditya_tilak@34.100.136.139"]
2025-03-13 04:10:16,804 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): compute.googleapis.com:443
2025-03-13 04:10:17,039 DEBUG    urllib3.connectionpool https://compute.googleapis.com:443 "GET /compute/v1/projects/cropcrafters-project/zones/asia-south1-c/instances/34.100.136.139?alt=json HTTP/1.1" 403 None
2025-03-13 04:10:17,044 DEBUG    root            Chosen display Format:list[title="Could not fetch resource:",always-display-title]
2025-03-13 04:10:17,045 DEBUG    root            (gcloud.compute.ssh) Could not fetch resource:
 - Request had insufficient authentication scopes.
Traceback (most recent call last):
  File "/snap/google-cloud-cli/293/lib/googlecloudsdk/calliope/cli.py", line 998, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/293/lib/googlecloudsdk/calliope/backend.py", line 843, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/293/lib/surface/compute/ssh.py", line 287, in Run
    instance = ssh_helper.GetInstance(client, instance_ref)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/293/lib/googlecloudsdk/command_lib/compute/ssh_utils.py", line 533, in GetInstance
    return client.MakeRequests([request])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/google-cloud-cli/293/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 145, in MakeRequests
    utils.RaiseToolException(
  File "/snap/google-cloud-cli/293/lib/googlecloudsdk/api_lib/compute/utils.py", line 139, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/snap/google-cloud-cli/293/lib/googlecloudsdk/api_lib/compute/utils.py", line 148, in RaiseException
    raise exception(
googlecloudsdk.calliope.exceptions.ToolException: Could not fetch resource:
 - Request had insufficient authentication scopes.

2025-03-13 04:10:17,048 ERROR    root            (gcloud.compute.ssh) Could not fetch resource:
 - Request had insufficient authentication scopes.

